### ISSUE TITLE
Cancelling a download in progress crashes the app

### ISSUE THREAD

**Issue by jdmswong** [vsivsi/meteor-file-sample-app#5]
If the X is clicked while downloading a large file, after a few seconds the client will throw a few of these:

```
HEAD http://localhost:4000/gridfs/fs/_resumable?resumableChunkNumber=22&resumabl….mp4&resumableRelativePath=myFile.mp4&resumableTotalChunks=228 404 (Not Found)
ResumableChunk.$.test @ resumable.js:648
ResumableChunk.$.send @ resumable.js:667
(anonymous function) @ resumable.js:848
$h.each @ resumable.js:137
(anonymous function) @ resumable.js:846
$h.each @ resumable.js:137
$.uploadNextChunk @ resumable.js:844
doneHandler @ resumable.js:691
```

Upon restart the partially downloaded file will reappear in the table, but cannot be resumed.  If the same file is dragged back in, it will create a new row and download normally there.

**Comment by vsivsi** [comment]
Fixed!  Thanks for reporting.

**Comment by jdmswong** [comment]
Thanks @vsivsi !

**Comment by vsivsi** [comment]
Note, there's no simple way to resume an interrupted upload by dragging the same file into the browser. There is no simple way (without reading in the entire file before each upload, which would be impractical for large files) to know if the file has changed between upload attempts, so resuming could result in corrupted files in the general case. It could be done if you somehow **know** that the file hasn't changed...
